### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by MakarkinPRO** [airnotifier/airnotifier#100]
When I type in Google Chrome http://my_ip:8801/api/v2/push

I receive:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 1323, in _execute
    result = self.prepare()
  File "/root/airnotifier/api/__init__.py", line 78, in prepare
    self.appname = filter_alphabetanum(self.get_argument('appname'))
  File "/usr/local/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 378, in get_argument
    return self._get_argument(name, default, self.request.arguments, strip)
  File "/usr/local/lib/python2.7/site-packages/tornado-4.1-py2.7-linux-x86_64.egg/tornado/web.py", line 447, in _get_argument
    raise MissingArgumentError(name)
MissingArgumentError: HTTP 400: Bad Request (Missing argument appname)

+++

Where I made a mistake?

ps: do you have to-do installation for CentOS 6.5 (64 bit)?

**Comment by dcai** [comment]
It says in the last line: MissingArgumentError: HTTP 400: Bad Request (Missing argument appname)

You must construct a valid http request with appname in http header, take a look at this example: https://github.com/airnotifier/test-scripts/blob/master/v2/push_gcm.php

**Comment by MakarkinPRO** [comment]
Is it possible to install 

require_once 'curl.class.php';

manually in linux console?

**Comment by MakarkinPRO** [comment]
I just tryin send BroadCast from admin area and in logs it says:

GCM problem

**Comment by dcai** [comment]
Have you setup GCM properly? https://github.com/dcai/android-gcm-client-app/blob/master/README

**Comment by MakarkinPRO** [comment]
Import this project into eclipse.
>>>I run new Android Studio project and added "compile 'com.google.android.gms:play-services:6.5.87'" into build.gradle file.

after that I imported by copy-paste all other files and changed String SENDER_ID = "to my into Google API ID project Number"<<<

>>>After I run the application and it says:

-10 16:00:01.938    2195-2195/com.test.myapplication I/GCM Demo﹕ APA91bFeILawoVo9V5Ps3APnfqpdYPGR8yN9zGkaIy4zj3XMXyLJafmVlyzb8TuQwgcspuimrGhevqt9CT7aLJG5i6hD62iaAIRP-I5Xoe9woKXGr2drViALNYBmWkcNXOdfQfTWOUzc1mKgrSmAbF5Hc4dDaPRr1aZQjE8NUemrMHYslgpqI-c
03-10 16:00:01.996    2195-2214/com.test.myapplication D/OpenGLRenderer﹕ Render dirty regions requested: true
03-10 16:00:01.999    2195-2195/com.test.myapplication D/﹕ HostConnection::get() New Host Connection established 0xa6b0fee0, tid 2195
03-10 16:00:02.068    2195-2195/com.test.myapplication D/Atlas﹕ Validating map...
03-10 16:00:02.197    2195-2214/com.test.myapplication D/﹕ HostConnection::get() New Host Connection established 0xa6b0f960, tid 2214
03-10 16:00:02.284    2195-2214/com.test.myapplication I/OpenGLRenderer﹕ Initialized EGL, version 1.4
03-10 16:00:02.310    2195-2214/com.test.myapplication D/OpenGLRenderer﹕ Enabling debug mode 0
03-10 16:00:02.331    2195-2214/com.test.myapplication W/EGL_emulation﹕ eglSurfaceAttrib not implemented
03-10 16:00:02.331    2195-2214/com.test.myapplication W/OpenGLRenderer﹕ Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6b61140, error=EGL_SUCCESS

<<<

>>>BUT the APP run on Google Nexus 5 with android version 5. It's have 2 buttong send and clear. When I click send its printing "Sent message" text into the app.<<<

1. you need to go through GCM setup: http://developer.android.com/google/gcm/gs.html, store project number in android app (take a look at DemoActivity.java, SEND_ID field), then add API key in airnotifier admin panel
>>>Yes I done it, but in my Android Studio I renamed file to MainActivity and changed SEND_ID. As well as added API into admin panel<<<

2. The android app requires external jars, so you need to take a look at http://developer.android.com/google/gcm/client.html and add google play services jars to the project

>>>I just added "added "compile 'com.google.android.gms:play-services:6.5.87'" into build.gradle file."<<<
3. The interesting part is GcmIntentService.onHandleIntent method, it extract the notification posted from AirNotifier, same as iOS platform, we use alert for notification message, additionally, android could process more params, just send all them to /notification/ endpoint

>>> What is /notification/ ? Am I need in for testing with Android deveice only?<<<

It's possible to run it in emulator, I did that on a physical device, please note you need to obtain the device registration id (known as token on iOS) from the LogCat console (set filter to tag:GCM) before sending messages from AirNotifier.

>>>Yes I run it on Android emulator <<<

On AirNotifier side:
1. Run upgrade.py script (backup existing mongodb data  of course)
>>>I need to done this everytime when restart AirNotifier.by?<<<
2. /notification/ endpoint requires device param, if not supplied, it would be considered to be an ios device
>>>Didn't get what here are talking about =?<<<
3. please use 'moodle' branch on github, it has moodle specific changes
>>>Yes I use it<<<

Am I need to PUSH "Launch" for APNs service. For testing only on Android device right now?

**Comment by MakarkinPRO** [comment]
and don't see anythin into /tokens into admin panel....

**Comment by onghuizi** [comment]
Hi MakarkinPRO,
I am facing the same problem also, "missing appname" , did you solve the problem? How you solve it?
