### ISSUE TITLE
Is it possible to detect connected (online devices)?

### ISSUE THREAD

**Issue by MakarkinPRO** [airnotifier/airnotifier#101]
Have a several qestions:

1) How to detect how may device is connected?
2) When device is goin offline or closing the app on the Phone is it possible to sent offline command
3) What the main purpose of tokens - does it cover two questions above?
4) Is I have alltoghether 1000 device which were installed one same app, and 300 of them is offline. Does messages will be delivered when they'll back online (and Am I receive A delivered status counter?)

**Comment by dcai** [comment]
1) impossible, read apple and gcm documents please
2) yes
3) token is your device identification
4) yes

I recommand you read thought apple's [APNS document](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html) before jump into the project.
