### ISSUE TITLE
How to register a token?

### ISSUE THREAD

**Issue by echarif** [airnotifier/airnotifier#105]
I need to register a token in my airnotifier server, but I don't know how to.

Thanks in advance.

**Comment by tfohlmeister** [comment]
https://github.com/airnotifier/airnotifier/wiki/API#add-tokens

**Comment by echarif** [comment]
Is there something more specific?, I don't understand it, it's very confusing. I'm sorry.
Thanks in advance.

**Comment by snehaldpatel1992** [comment]
your mobile app should have code that sends HTTP post request with token to your Air notifier server

**Comment by pacifire** [comment]
@snehaldpatel1992 : I wrote a code using "HttpURLConnection", It is working fine.

But what should be the URL ? Where shud i hit the URL to save the token in Airnotifier....

**Comment by pacifire** [comment]
@tfohlmeister : I referred this link : https://github.com/airnotifier/airnotifier/wiki/API#add-tokens
It says : "App has to send the device token to AirNotifier via RESTful API", 

But at what link ? http://localhost:8801/.....?

**Comment by tfohlmeister** [comment]
@pacfire You realize that airnotifier is a server application which runs on it's own? It's a python app. Please follow https://github.com/airnotifier/airnotifier/wiki/Installation and make sure you can reach the web UI before you try to register tokens.

**Comment by pacifire** [comment]
@tfohlmeister : Already, realized & reached the WEB UI successfully.
Also, got the answer for my doubt : 

For registering tokens with Airnotifier use : http://localhost:8801/api/v2/tokens
& for sending push Notifications use : http://localhost:8801/api/v2/push

For detailed parameters & documentation read : https://github.com/airnotifier/airnotifier/wiki/API#add-tokens
