### ISSUE TITLE
Provide a Dockerfile for Docker usage

### ISSUE THREAD

**Issue by fatalaa** [airnotifier/airnotifier#109]
It would be cool if there would be a Dockerfile in this repo so this app could run in a container environment.

**Comment by dcai** [comment]
Sounds like a good idea, I will try to make one. Thanks

**Comment by fatalaa** [comment]
I wrote a Dockerfile and a docker-compose.yml file for separating the MongoDB and the Airnotifier service, but I had to modify the config. Still interested?

**Comment by dcai** [comment]
@fatalaa Yes go for it :+1:

**Comment by jeremycod** [comment]
@fatalaa Did you ever finish this Dockerfile? Is it available somewhere?

**Comment by cyberhiker** [comment]
Any chance you could provide you Dockerfile and docker-compose.yml?

**Comment by fatalaa** [comment]
Absolutely no chance, these branch was on my former company's server, and I have no access to it anymore.

**Comment by AnthoDingo** [comment]
Hello,
Check this pull request : https://github.com/airnotifier/airnotifier/pull/157
