### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by euxneks** [airnotifier/airnotifier#114]
Hey I did an initial conversion to python3 here:

https://github.com/euxneks/airnotifier/tree/python3

Let me know if you want me to make a pull request or something. I'm not entirely certain it works 100% because I haven't got an app to push to yet :sweat_smile:

**Comment by dcai** [comment]
woo very nice thanks @euxneks, do you mind I mirror your branch to my repo? not sure if I should merge to master yet, because a lot of people still use python 2.7.*

**Comment by euxneks** [comment]
Certainly - it's not really my code is it! :grinning: I'd be happy to have other eyes look at it too - I'm not sure if I missed anything, I'm pretty certain I've merged from your main branch up to that last change 10 days ago...

**Comment by dcai** [comment]
Thanks @euxneks, I added python3 branch to my repo: https://github.com/airnotifier/airnotifier/tree/python3
