### ISSUE TITLE
Mismatch sender Id

### ISSUE THREAD

**Issue by vmusica** [airnotifier/airnotifier#115]
Hi. I'm having problem with AirNotifier.
We are trying to implement AN to support our Moodle, and Moodle 2.9 and AN are connected and tokens are created for devices. But when AN tries to contact GCM, I get this output: 

GCM problem: Mismatch sender Id

What is the cause of this? We have GCM certificate (server), correct project ID... What could be wrong?

**Comment by dcai** [comment]
@vmusica that error comes from GCM server. does this link help?

http://stackoverflow.com/questions/11313342/why-do-i-get-mismatchsenderid-from-gcm-server-side/11313861#11313861

**Comment by pacifire** [comment]
@vmusica : Please check your Project ID from your developer account.

Please don't use Project Name, instead use Project Number.

**Comment by srinathvsp** [comment]
please check ur app is singed apk or not if singed apk ur problem will be resloved. Because i also got same problem after awhile its resolved
