### ISSUE TITLE
Add user profiling

### ISSUE THREAD

**Issue by teopost** [airnotifier/airnotifier#117]
Very nice project , but it would need to add the user profiling in order to send a message to a specific user

**Comment by fatalaa** [comment]
I already implemented this but it's not compatible  with codebase. Maybe I'll open a PR about this

**Comment by teopost** [comment]
Airnotifier is very well done, but i think this feature should be
implemented in the master branch.
Where can i find your version?
Il 10/ott/2015 16:32, "Tibor Molnár" <notifications@github.com> ha scritto:

**Comment by fatalaa** [comment]
You cannot find it on Github, but I'll make a patch to make it available in the master

**Comment by teopost** [comment]
Thanks
Il 10/ott/2015 04:50 PM, "Tibor Molnár" <notifications@github.com> ha
scritto:
