### ISSUE TITLE
Airnotifier is running but API is not found

### ISSUE THREAD

**Issue by jeremycod** [airnotifier/airnotifier#127]
Hi,

I installed [Moodle version of Airnotifier](https://github.com/moodlehq/airnotifier/tree/moodle2). Web UI works fine and I was able to configure it as given in the screenshots bellow. However, when I try to run [test](https://github.com/airnotifier/test-scripts/blob/master/v2/push_gcm.php), I got the 404 error that /api/v2/push was not found.

```
string(306) "Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```

My airnotifier.err log also contains warning:
`WARNING 404 POST /api/v2/push (192.168.2.68) 2.15ms`

I guess this is something related to my configuration, but I'm not sure what should I check. I believe that I did everything as described in installation instructions.

This is my configuration:
![selection_099](https://cloud.githubusercontent.com/assets/5204745/11594761/a67b8684-9a60-11e5-8e2f-b32321894c6a.png)

![selection_100](https://cloud.githubusercontent.com/assets/5204745/11594773/b29c2518-9a60-11e5-8165-f70d8fbe448d.png)

![selection_101](https://cloud.githubusercontent.com/assets/5204745/11594775/b7a5f61a-9a60-11e5-8506-e1dda0534ceb.png)

**Comment by dcai** [comment]
@jeremycod I have no clue how this could happen, are you running airnotifier on the same machine as push_gcm.php script?

**Comment by jeremycod** [comment]
No. It's in local network. Push_gcm. php is on the other computer.  Since file exposing these service is there I guess service is not visible for some reason. However I'm not familiar with Python to investigate it deeper.
