### ISSUE TITLE
Change Collapse Key in GCM

### ISSUE THREAD

**Issue by pacifire** [airnotifier/airnotifier#128]
How do we change the Collapse key for GCM.

Currently the collapse key is : collapse_key = do_not_collapse
I want to change this.

Whenever i hit : http://localhost:8801/api/v2/push
I get response as : 
[{
	from = 341778046954, message = alert1 with scoreUpdate, android.support.content.wakelockid = 4, collapse_key = do_not_collapse
}]

But i want to change this collapse_key.
GCM supports maximum 4 different, collapse_key. How do i edit collapse_key using Airnotifier.

**Comment by dcai** [comment]
@pacifire I believe it's here: https://github.com/airnotifier/airnotifier/blob/1.x/pushservices/gcm.py#L89

**Comment by pacifire** [comment]
@dcai : Thanks alot.
Thanks for the help. :+1:
