### ISSUE TITLE
'module' object has no attribute 'create_default_context'

### ISSUE THREAD

**Issue by Johndavidsanford** [airnotifier/airnotifier#136]
Using PHP 5.5.9-1ubuntu4.14 I am getting the following traceback when starting AirNotifier server:
```
Traceback (most recent call last):
  File "airnotifier.py", line 285, in <module>
    AirNotifierApp(services=services).main()
  File "airnotifier.py", line 193, in main
    ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
AttributeError: 'module' object has no attribute 'create_default_context'
```
Any clues?  I have gone though all of the previous suggestions and added the suggested packages, but I believe this to be an environmental issue.

**Comment by Johndavidsanford** [comment]
I stumbled onto something that seems to make sense when debugging.  It is looking like a misleading pem error as this is the section that is the cause of the error:
```
           try:
                ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
                ssl_ctx.load_cert_chain(options.httpscertfile, options.httpskeyfile)
            except IOError:
                print("Invalid path to SSL certificate and private key")
                raise
```

**Comment by Johndavidsanford** [comment]
Upon further investigation the applications collection in the mongodb is empty.  What would cause this?

**Comment by Johndavidsanford** [comment]
I was able to get further by turning off the SSL

**Comment by charterresources** [comment]
I had the same issue. It is because of the default python (2.7.6) version ubuntu is using. Upgrading ubuntu to 15.10 which in turn upgraded the python version to 2.7.10 resolved it.

**Comment by dcai** [comment]
Hi @Johndavidsanford you need to upgrade your python to 2.7.9 or up.

**Comment by dcai** [comment]
@charterresources :+1:

**Comment by sftranna** [comment]
You can alternatively use (for python 2.6) this code to disable the ssl certificate verification 
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
    ctx.check_hostname = False
    ctx.verify_mode= ssl.CERT_NONE
