### ISSUE TITLE
"extra" gets ignored by Airnotifier

### ISSUE THREAD

**Issue by hernan43** [airnotifier/airnotifier#140]
I am admittedly completely beginner level when it comes to push notifications in general so I apologize in advance if I am completely dumb about this. I have sites that use Moodle that we would like to use push notifications with inside of a custom deployment. 

Moodle has built-in support for Airnotifier. When it sends a push notification to Airnotifier it sends a data structure that looks something like this:

```
{
  "aps": {
      "alert": "- From: Joe Schmoe - Subject: RE: My great message"
  },
  "extra": {
    "processor":"moodle",
    "data":{"key1":"param1 value","key2":"param2 value"}
  }
}
```

For some reason Airnotifier strips off the "extra" section when it actually gets delivered to the APNS service. Looking in the code it _seems_ as though it is going to pass along that "extra" section but if you follow the chain of execution the "extra" gets dropped.

In the iOS device type section in push.py is is sending the 'extra' data into the APNS client processor:

https://github.com/airnotifier/airnotifier/blob/1.x/api/push.py#L126

But in the process method for the APNS client, the 'extra' parameter is never used:

https://github.com/airnotifier/airnotifier/blob/1.x/pushservices/apns.py#L284

Is there a reason for this?

**Comment by armandzwan** [comment]
You need to put it in the "custom" field
"custom": {
    "processor":"moodle",
    "data":{"key1":"param1 value","key2":"param2 value"}
  }
