### ISSUE TITLE
Run as service

### ISSUE THREAD

**Issue by SvenKortekaas** [airnotifier/airnotifier#145]
Hello, I'm running the server in a virtualmachine on a Ubuntu server with the standard comment:
`sudo python airnotifier.py >> airnotifier.log 2>> airnotifier.err`
But now the user is logged in and I can't do anything on the server. Is there a way to run it as a service or something? 

My linux skills are limited, I'm sorry.

EDIT: Now I'm using "screen"

Side note: I created a simple small broadcast app for AirNotifier, maybe usefull for some of you - https://play.google.com/store/apps/details?id=nl.skortekaas.airnotifierpusher

**Comment by kdbz** [comment]
Hi SvenKortekaas,

Kindly do the following (On Ubuntu):

1. Create an upstart config file at /etc/init/airnotifier.conf
2. Edit the contents of the file to your directories accordingly to point to your airnotifier folder e.g

`description "Airnotifier Service"
author "Airnotifier Team"

start on (local-filesystems and net-device-up)
stop on runlevel [06]

chdir /home/user/airnotifier
exec /home/user/airnotifier/airnotifier.py >> /home/user/airnotifier/airnotifier.log 2>> /home/user/airnotifier/airnotifier.err
respawn

3. Set the permissions of the conf file to 644 
  `$ sudo chmod 644 /etc/initctl/airnotifier.conf`
4. Reload the upstart service 
  ` $ initctl reload-configuration`
5. Run airnotifier as a service
  `$ sudo start airnotifier`

 And that's it!

Cheers.

**Comment by Dirk23** [comment]
@kdbz there is only one little typo in your Code. Instead of `sudo chmod 644 /etc/initctl/airnotifier.conf` it should be `sudo chmod 644 /etc/init/airnotifier.conf`

**Comment by Dirk23** [comment]
How do i do the same on Ubuntu 16.04 without upstart?

**Comment by kdbz** [comment]
@Dirk23  Thank you for the modifications.

Ubuntu 16.04 uses systemd,kindly refer to the following on how to convert from upstart to systemd

- https://wiki.ubuntu.com/SystemdForUpstartUsers
- http://serverfault.com/questions/785502/create-daemon-on-ubuntu-16-04
- https://www.digitalocean.com/community/questions/convert-run-at-startup-script-from-upstart-to-systemd-for-ubuntu-16

**Comment by paymanzafar** [comment]
According to the above posts, the airnotifier.service file should be as follows:
[Unit]
Description=Airnotifier Service
After=default.target

[Service]
Type=forking
User=admin
WorkingDirectory=/home/admin/airnotifier
ExecStart=/home/admin/airnotifier/airnotifier.py >> /home/admin/airnotifier/airnotifier.log 2>> /home/admin/airnotifier/airn$
Restart=always

[Install]
WantedBy=default.target

But after enabling & starting this service, it will not use the .err & .log files.

**Comment by ceremy1** [comment]
@paymanzafar  i have same problem . Did u find any solution?
