### ISSUE TITLE
Could not send message with APNS

### ISSUE THREAD

**Issue by Itchythefirst** [airnotifier/airnotifier#146]
Hello, we are unable to send message with APNS to the device in sandbox mode(haven't tried in production mode).

Everything seems to be set correctly. 
When we add token, we get code 200 - OK.
When we send the notification, we get code 202 -accepted.
But no message is ever received on the device.
In the web AirNotifier app in the Logs section we see that there is an action notification with our app.
We tried to send the the notification to the device using APN tester and it was received.

Could you give us a hint what could be the issue?

Thanks.

**Comment by jakubTraveler** [comment]
Hi, re-installation and re-uploading the certificates solved the issue.

**Comment by arkilis** [comment]
Spent hours on installation and setup. Not working for me.
