### ISSUE TITLE
Production Push Notification Certificate -- Not receiving APN Notifications

### ISSUE THREAD

**Issue by pacifire** [airnotifier/airnotifier#151]
https://github.com/airnotifier/airnotifier/wiki/Installation#ios-push-notification-settings

I read above link & followed successfully for development profile.
Please, can somebody help me with Production Profile steps.

I tried creating Production certificate & going through the same steps but, i am not receiving Push Notifications via Airnotifier.

**Comment by tibimate87** [comment]
hello @pacifire, did you find any solution to this problem? Thanks in advance!
