### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by basemwahba** [airnotifier/airnotifier#152]
Hi,

I got four files as a result of my certificate request:
cert1.pem
chain1.pem
fullchain1.pem
privkey1.pem

Below is my _airnotifier.conf_ configuration file:

```
https = True
httpscert = "/Users/basemwahba/airnotifier/cert/fullchain1.pem"
httpskey = "/Users/basemwahba/airnotifier/cert/privkey1.pem"

port = 8801

pemdir = "/Users/basemwahba/airnotifier/cert"

passwordsalt = 'd2o0n1g2s0h3e1n1g'
cookiesecret = 'airnotifiercookiesecret'
debug = False

mongohost = "localhost"
mongoport = 27017

masterdb = "airnotifier"
collectionprefix = "obj_"
dbprefix = ""
appprefix = "app_"
```

After I start Airnotifier, I get the following:

```
Basems-Mac-Pro:airnotifier basemwahba$ python airnotifier.py
[I 160601 23:32:34 airnotifier:189] Starting AirNotifier server
Invalid path to SSL certificate and private key
Traceback (most recent call last):
  File "airnotifier.py", line 285, in <module>
    AirNotifierApp(services=services).main()
  File "airnotifier.py", line 194, in main
    ssl_ctx.load_cert_chain(options.httpscertfile, options.httpskeyfile)
IOError: [Errno 2] No such file or directory
```

Any help is really appreciated.

Thanks.

Regards  
![1](https://cloud.githubusercontent.com/assets/14953296/15726934/dabbd0b2-2853-11e6-979f-d3c9c191e3d2.jpg)
![2](https://cloud.githubusercontent.com/assets/14953296/15726935/dac4aac0-2853-11e6-9940-4ef46850adb6.jpg)
![3](https://cloud.githubusercontent.com/assets/14953296/15726936/daca737e-2853-11e6-8f9a-0d3f269ae1ba.jpg)

**Comment by rahul-chowdhary** [comment]
Hi, @basemwahba I am facing the same issue. have you found any solution? 
Any help is really appreciated.

**Comment by akuldaev** [comment]
If you are not going to use SSL, change the first line  "https = False"
