### ISSUE TITLE
Notifications Not arriving at the Mobile App

### ISSUE THREAD

**Issue by toluka** [airnotifier/airnotifier#159]
Dear Team
I have setup airnotifier for my customised Moodle Mobile App (ug.ac.mubs.mubsep) Mobile Mubsep (Google Play Store)
I followed all the instructions and indeed the airnotifier is running. However when i try to sent a brodcast message nothing appears. I have the Airnotifier plugin installed at my Moodle Site and have changed the settings including Airnotifier access key that I generated from Google Developer. Any help would be appreciated.

Tony Uganda

**Comment by wa8w1r3** [comment]
i tried mubsep airnotifier and i got distorted pass pass pass
