### ISSUE TITLE
Putting AirNotifier behind a Nginx Reverse Proxy

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [airnotifier/airnotifier#160]
I would like to know if anyone has any experience in putting the AirNotifier behind a Nginx Reverse Proxy. I am following the same drill in setting up the Nginx config for Node.js Instances and setting up AirNotifier to run on HTTP. But I get this: 

`Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1390, in _execute
    result = self.prepare()
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2103, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found`

Being not articulate at all in the Tornado framework, I can't really figure out what has gone wrong... Please help.

**Comment by ypshukla** [comment]
You can run the Airnotifier with Nginx by using proxy 
**location / {
        proxy_pass http://IP_Address:8801;
        }**
