### ISSUE TITLE
error on start, related to https

### ISSUE THREAD

**Issue by gdbjohnson** [airnotifier/airnotifier#163]
Hello, 

I'm getting the following error which may be related to my certificate.  I followed the steps at http://www.thegeekstuff.com/2009/07/linux-apache-mod-ssl-generate-key-csr-crt-file/ to create my certificate, and I have a path to the generated files defined in the config.  When I turn Https: False, the server starts (although I can't access it via the browser for some reason, possibly unrelated).

What am I missing?

```
[I 170124 22:12:18 airnotifier:189] Starting AirNotifier server
Traceback (most recent call last):
  File "airnotifier.py", line 285, in <module>
    AirNotifierApp(services=services).main()
  File "airnotifier.py", line 193, in main
    ssl_ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
AttributeError: 'module' object has no attribute 'create_default_context'
```

**Comment by dcai** [comment]
Looks like you are using very old python version, you might need to upgrade to python 2.7
