### ISSUE TITLE
Best way to always run airnotifier

### ISSUE THREAD

**Issue by Daniel-Gherard** [airnotifier/airnotifier#173]
I would like to thank every one who helped this project. It's an amazing work.

Right now, I'm wondering what would be the best way to ensure Airnotifier is always running.

I have a machine which has a Moodle and an Airnotifier installations. But, to run the Airnotifier, I have to connect to this machine using SSH and run the command:

sudo python airnotifier.py >> airnotifier.log 2>> airnotifier.err

The problem is that this machine often restarts, so Airnotifier stops too.
As far as I'm aware a Cronjob would not work, because of the need of a sudo privileges. 

Anyone could help me with that?

**Comment by dcai** [comment]
@Daniel-Gherard I suggest you setup airnotifier with this: http://supervisord.org/

**Comment by Phoenix09** [comment]
> As far as I'm aware a Cronjob would not work, because of the need of a sudo privileges.

If it's in the system crontab it would be executed as root unless you specify otherwise.

I use systemd:
```
[Unit]
Description=AirNotifier
After=syslog.target network.target

[Service]
Type=simple
ExecStart=/opt/airnotifier/airnotifier.py
KillMode=process
KillSignal=SIGINT
Restart=on-failure
WorkingDirectory=/opt/airnotifier
User=www-data
Group=www-data

[Install]
WantedBy=multi-user.target
```

**Comment by Daniel-Gherard** [comment]
Thanks, @Phoenix09!
Worked great for me.
