### ISSUE TITLE
"category" does not appear in aps dictionary

### ISSUE THREAD

**Issue by AnthonyUccello** [airnotifier/airnotifier#175]
I'm sending a payload

`curl -H "Content-Type: application/json" -H "X-AN-APP-NAME:myapp" -H "X-AN-APP-KEY:appkey" -X POST -d '{"device":"ios","token":"1234","alert":"Hi","sound":"hi.aff","badge":2,"category":"myCategory"}' http://localhost:8801/api/v2/push
`
When I observe the result in `aps` dictionary I get this:

Optional({
    alert = Hi;
    badge = 2;
    sound = "hi.aff";
})

I believe category is getting ignored

Also looking in the UNNotification object I see the category is nil:

`<UNNotificationContent: 0x1744e4100; title: (null), subtitle: (null), body: Hi, categoryIdentifier: , ...>`

**Comment by voldzi** [comment]
Any news on this? I'd like to also use "category"...
