### ISSUE TITLE
Supported Protocols

### ISSUE THREAD

**Issue by ibr123** [airnotifier/airnotifier#184]
Hi, 

i saw in the website of the [AirNotifier](http://airnotifier.github.io/) the supported protocols, i saw that for android, the protocol is GCM but i didn't notice any mention of the protocol FCM.

is FCM protocol supported in AirNotifier? Since GCM is deprecated 

Thanks

**Comment by dcai** [comment]
Hi @ibr123 FCM protocol is not supported.
