### ISSUE TITLE
Installed airnotifier but cant log in

### ISSUE THREAD

**Issue by Dirk23** [airnotifier/airnotifier#186]
Hi,

i just followed the installation instruction to install airnotifier on my Ubuntu 16.04, but after i started airnotifier i can not log in with admin/admin. I guess i have some old Database of a prior installation of airnotifier where the password is something i dont remember. Is there a way to delete the old database?

**Comment by Dirk23** [comment]
Ok, i found out how to drop the database and i can now log in, but im am not able to change the password of admin and i can not add other users,

**Comment by dcai** [comment]
Please go to users link in left side, there is change password button next to your username.
