### ISSUE TITLE
Support for firebase?

### ISSUE THREAD

**Issue by ft9292** [airnotifier/airnotifier#187]
As you can see in the GCM page, it's been deprecated since April 10, and everything is moving to Firefbase
Link: https://developers.google.com/cloud-messaging/

Any plans for supporting FCM in the near future?

**Comment by ft9292** [comment]
https://developers.google.com/cloud-messaging/android/android-migrate-fcm

The API hasn't changed much, it shouldn't be hard to port GCM to FCM

**Comment by dcai** [comment]
@ft9292 I have updated fcm endpoint, can you please verify if it works?

**Comment by malinchhan** [comment]
hi, I test adding token and it doesn't work if token is firebase format for iOS. Any solution ? Now it only accepts APNs token.

**Comment by dcai** [comment]
@ft9292 @malinchhan if you are using iOS with fcm support, please use FCM service, not apple apns.
