### ISSUE TITLE
Required Open Ports

### ISSUE THREAD

**Issue by paymanzafar** [airnotifier/airnotifier#189]
Hi all,
Is there any need to open any outbound port on Airnotifier server?
Thanks.

**Comment by dcai** [comment]
yes, the default port is 8801

**Comment by Lancemaker** [comment]
i had this same problem. open the 8801 on the server and make sure (if you are using windows) to allow it to as a new firewall rule. The way i tested was : i disabled everything from certificates and firewalls on the server oppened the 8801 on the server also 80( not sure if its necessary but still). On the client side i disabled the windows firewall and it worked.
