### ISSUE TITLE
Thirtydaysago in base.py does not have the right count

### ISSUE THREAD

**Issue by R2D2byBest** [airnotifier/airnotifier#193]
Hi,

Just a little fix, in the  airnotifier/controllers/base.py line 159 you have : 

**thirtydaysago = now - 60 * 60 * 24** (it's just 24 hours)

But the right count for thirtydays is  60 * 60 * 24 * **30**.

It's a pleasure to contribute.

Thank You

**Comment by dcai** [comment]
Thank you!
