### ISSUE TITLE
Disabling GCM and forcing use of FCM?

### ISSUE THREAD

**Issue by mugwhump** [airnotifier/airnotifier#199]
So I recently upgraded my server to the latest FCM branch which seems good, my project now has a place to set my firebase settings. However there doesn't seem to be any way to 'unset' the existing gcm settings and make airnotifier actually use firebase instead of gcm. You're unable to delete the gcm settings, and replacing them with '0' or some other garbage will just cause the message to fail.

Is there any way to do this without creating a new app?

Edit: so I went and made a new app with nothing but FCM configured, and I'm just getting an error with "500 POST /api/v2/push/" and no other details. My original app works fine with GCM, I'm not sure where the problem is.

**Comment by lkstnr** [comment]
Anybody got FCM working with AirNotifier?

**Comment by mugwhump** [comment]
OK, it seems that if you keep using the same old existing GCM settings in the same place, it uses the new fcm endpoints. Everything appears to work fine. I guess those "firebase" settings are for a different type of project.
