### ISSUE TITLE
Problem sending Persian Characters with FCM

### ISSUE THREAD

**Issue by paymanzafar** [airnotifier/airnotifier#203]
I have installed the fcm branch, and it can not send Persian characters with FCM, but it can send with GCM.
I added the following code to airnotifier.py, and now it can send some Persian texts, but not all.

import sys
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by dcai** [comment]
Hi @paymanzafar can you share the Persian text you use for testing?

**Comment by paymanzafar** [comment]
Hi dcai,
Here it is:
نسخه جدید نرم افزار مگ آموز برای سیستم اندروید آماده نصب است. لطفا به آدرس زیر مراجعه نمایید:

**Comment by dcai** [comment]
@paymanzafar thank you, I will find some time this week to get this resolved.

**Comment by dcai** [comment]
@paymanzafar I have pushed a fix to 1.x branch, can you update the code and try again?

**Comment by paymanzafar** [comment]
Hi dcai,
Thank you very much for your time, but as I explained in the first comment, this problem is in fcm branch. I have already used version 1.x, and there was no problem with GCM notifications.
