### ISSUE TITLE
Airnotifier not registering tokens

### ISSUE THREAD

**Issue by rec16005** [airnotifier/airnotifier#205]
I have an airnotifier server for my moodle custom app but it is not registering tokens. The tokens are being registered in moodle as intended but not on the airnotifier.

I am using 2.x branch as advised by developers in this issue https://github.com/airnotifier/airnotifier/issues/195 

My server is in AWS.

**Comment by dcai** [comment]
@rec16005 in moodle airnotifier, can you check if mobile app name matching your actual app name? you can verify this by checking the app name in `mdl_user_devices` table in moodle.

If airnotifier not getting tokens it's mostly a moodle configuration issue.

**Comment by rec16005** [comment]
Yes it matches, I thought that was the problem so I recently changed it. 
On the other hand, is it a problem that my table is named mdlih_user_devices instead of just mdl_user_devices? I don't know why is it called that way but does it affect?

**Comment by dcai** [comment]
@rec16005 most of time `mdl_user_devices` is the right name, `mdl_` is a config option defined in config.php, please check the table prefix option. could you send me some records (hide devices token data please) in user devices table and airnotifier config in your moodle, so I can investigate?

**Comment by dcai** [comment]
closing as the issue has been resolved.
