### ISSUE TITLE
Last Stable Build without new APNs implementation of HTTP/2

### ISSUE THREAD

**Issue by pepecoco** [airnotifier/airnotifier#207]
Hi Dcai,

We have been installing your latest build a moment ago to get APNs working however we can see you making changes due to issues/bugs.

e.g. read_until_close() takes 1 positional argument but 2 were given

May I ask if you can point me to a zip file (stable build) where APNs was working?

Thanks,
Peter

**Comment by dcai** [comment]
@pepecoco 2.x branch has http/2 apns implementation, you could download from here: https://github.com/airnotifier/airnotifier/archive/2.x.zip

Please follow the installation guide: https://github.com/airnotifier/airnotifier/wiki/Installation-2.x

**Comment by pepecoco** [comment]
Thanks Dcai. Appreciate your efforts! Thanks from Perth WA.

**Comment by dcai** [comment]
@pepecoco just to clarify, I'm working on http/2 apns to replace legacy tcp based apns protocol, I pushed everything to 2.x branch just a few minutes ago, but now I realize this might be a bad idea and have impact on existing users, so I have reverted the changes, 2.x branch has the legacy apns protocal, ill tag the http/2 version in a major version release. Ill keep you posted.

**Comment by dcai** [comment]
I have decided to tag the http/2 apns as 3.x release, you can download from https://github.com/airnotifier/airnotifier/archive/v3.0.0-alpha.0.zip
and the installation guide is:
https://github.com/airnotifier/airnotifier/wiki/Installation-3.x

**Comment by pepecoco** [comment]
Thanks for creating a new branch. We downloaded the latest/installed this morning in hope for better logging. After a while, we managed to get it back up with new errors hence the initial question. 

Would be great if there is a document on how to reinstall or remove airnotifier totally from a system in readiness for a new installation should upgrade.py fail.

We also noticed install.py, there were 2 define arguments for pemdir and that prevented us from installing. We removed 1 and it was fine.   

I am very new to programming and have not much python experience at all. Only JS ;(

Thanks again.

**Comment by dcai** [comment]
@pepecoco if you start new, you probably want to try the new release as it doesn't need pemdir anymore, http/2 apns is much easier to config.

btw are you using airnotifier for moodle integration?

**Comment by pepecoco** [comment]
Correct, we are using airnotifier for moodle intergration and mobile app. We have luck with FCM where our apk app is getting notified. However, we are struggling to get ios app to work. 

So are you saying that we don't need a .pem and .key for APNs? just the FCM project id from firebase and json key will do?  i.e moodle site to have the right access key from air notifier and regardless of device, all can utilise FCM?

apologies if I am not using the right terminology, very new to this.

**Comment by dcai** [comment]
@pepecoco you don't need to setup apns in airnotifier, all moodle push notifications go through FCM, you only need to setup ios app in firebase console, please read this:

https://firebase.google.com/docs/cloud-messaging/ios/certs
https://firebase.google.com/docs/cloud-messaging/ios/client

**Comment by pepecoco** [comment]
Thanks for the links, we tried it out and the root cause was the xcode/local machine. We uploaded to apple store and it was working. i,e without using APNS settings at Airnotifier
