### ISSUE TITLE
About The keys. 

### ISSUE THREAD

**Issue by Lancemaker** [airnotifier/airnotifier#210]
Hi ! 
Im having problems configuring the keys. im pretty new to this. 
i generated a key and a csr files. and those lines look like this : 
https = True
httpscertfile = "/var/airnotifier/pemdir/server.csr"
httpskeyfile = "/var/airnotifier/pemdir/server.key"
pemdir = "/var/airnotifier/pemdir"

the files are in /ect/airnotifier/pemdir/

the program is installed in : /home/myUser/airnotifier/

if i turn https off the server works. Is it absolute necessary to use the keys ? 

and i keep getting this error : 

Invalid path to SSL certificate and private key
Traceback (most recent call last):
  File "./app.py", line 312, in <module>
    AirNotifierApp(services=services).main()
  File "./app.py", line 217, in main
    ssl_ctx.load_cert_chain(options.httpscertfile, options.httpskeyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3503)

im using the airnotifier 3 and im planning on using firebase to receive the moodle notifications on mobile. Thanks on making this application, i guess its the only way to make it work afaik.

**Comment by dcai** [comment]
@Lancemaker I just tested https with the certificates I generated, it works, no issues, so it might be something to do with the keys you generated.

yes, you can turn it off for testing, but if you use it in production environment, you could setup https in nginx or apache and reverse proxy to airnotifier.
