### ISSUE TITLE
APNs cert and key error on ver20190826

### ISSUE THREAD

**Issue by ptoptsis** [airnotifier/airnotifier#213]
When I try to upload my APNs pem and key I get the followig error
write() argument must be str, not bytes

I just upgraded to this version. How can I complete the upload?

**Comment by dcai** [comment]
@ptoptsis  could you please try v3.0.0-alpha.2? (https://github.com/airnotifier/airnotifier/releases)
v3 releases has implemented apple's apns http/2 protocol, it's much easier to setup.

**Comment by ptoptsis** [comment]
Thank you for the reply. Could you please quide me to install v3. The installation guide for v3 gives me the error 
Error: the command ./install.py could not be found within PATH or Pipfile's [scripts].
at pipenv run ./install.py

**Comment by dcai** [comment]
@ptoptsis are you using linux or mac? can you run `chmod a+x ./install.py`?
