### ISSUE TITLE
Error SENDER_ID_MISMATCH

### ISSUE THREAD

**Issue by pandaroma** [airnotifier/airnotifier#219]
Hello everyone

The installation guide 3.x is very easy and clear. But when I send a message to a registered user (moodle mobile app android), I get this message:

`{ "error": { "code": 403, "message": "SenderId mismatch", "status": "PERMISSION_DENIED", "details": [ { "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError", "errorCode": "SENDER_ID_MISMATCH" } ] } }`

The FCM JSON-file was created and copied like in the guide.

Any ideas?

pandaroma

**Comment by dcai** [comment]
@pandaroma  please see this doc: https://firebase.google.com/docs/reference/fcm/rest/v1/ErrorCode
it could be a bad device ID being logged in moodle or airnotifier.

**Comment by pandaroma** [comment]
Thanks for this hint.

- The name of the application in airnotifier ist the same as in the field airnotifierappname in moodle
- I've deleted all tokens in airnotifier. When I send a message, the token appears again and the error message is in the logs.
- I created a new private key in firebase (androidsdk) and copied the content of the json file in the right field of the FCM settings in airnotifier

Do you have any other idea? I use the moodle app from google play store. Do I need to compile my own moodle app?
Thanks in advance,
pandaroma

**Comment by pandaroma** [comment]
Now, I can answer my last question for myself: you have to compile your own moodle app (with the google-services.json of your project in it). 
Then, it works reliable and fast.
Thank you.
pandaroma
