### ISSUE TITLE
App Crash on Push Notification while in Foreground 

### ISSUE THREAD

**Issue by MRafiqAsim** [airnotifier/airnotifier#237]
Hi, I setup lasted version on my vps, when i send notification it is being received in notification tray along with title, and alert sound.
but only if the app is in background, If app is in foreground app crash instantly. Please any body who faced and fixed this issue.

**Comment by alexmorrisnz** [comment]
Hi @MRafiqAsim Are you using the moodle app? if so we made a fix for this issue here: https://github.com/catalyst/airnotifier/commit/53071af20d11c2c98352a31fb5d34837a4286b7a
based on the tracker issue MOBILE-3824
