### ISSUE TITLE
module: pymongo not found

### ISSUE THREAD

**Issue by bi1101** [airnotifier/airnotifier#243]
I've been trying to install Airnotifier 3 for over a week now and constantly get the error pymongo not found even though I have installed it and follow almost everything online to debug this. Has anyone come across this issue and solved it? I'm using Google cloud ec2 and AWS ec2, both of them return this error. Both are running Ubuntu 18.04 LTS

**Comment by bi1101** [comment]
found a fix

**Comment by MalikHourani** [comment]
how did you fix it ?
