### ISSUE TITLE
Getting MismatchSenderId error when posting to android.googleapis.com

### ISSUE THREAD

**Issue by hitteshahuja** [airnotifier/airnotifier#80]
Trying to implement my own Airnotifier server for Push notifications for Android. I believe I have reached the last stage where when sending a message ( say from Moodle desktop to Moodle app),I get a 500 POST /notification and the response is something like {failure: 1 ,......[{'error': 'MismatchSenderId'}]

A google search suggests that the regids that is being sent to the GCM server is wrong somewhere but I cant see where because doesn't Android give this reg id to my Android device . I can confirm that my API project number and my API key are correct.

**Comment by srinathvsp** [comment]
create server key from developer console and enable gcm after copy api key and project number put in ur custom app.then generate signed apk its get resloved. note:change **gcmpn** in  config.json
