### ISSUE TITLE
GCM problem: There was an error authenticating the sender account.

### ISSUE THREAD

**Issue by SimoneCarnio** [airnotifier/airnotifier#86]
[E 141025 19:04:58 airnotifier:132] GCM problem: There was an error authenticating the sender account.

I get this error in the log, and if I try to send notification with curl directly to google service the notification is sent.

I'm trying to debug the issue but I can't find a solution

**Comment by MakarkinPRO** [comment]
how did you figure out?

**Comment by MuneebSarfraz94** [comment]
in my case error returns against few cases only
