### ISSUE TITLE
APNs connection problems

### ISSUE THREAD

**Issue by SimoneCarnio** [airnotifier/airnotifier#92]
APNs certificate loading and production/sandbox mode switch is not working very well.

I have this recurring error 

```
[W 141115 22:45:43 apns:165] 1_1[0] is offline 1
[I 141115 22:45:44 apns:222] APNs connection: 1_1[0] is online
```

when:
- create a new app
- click on "production mode"
- upload certificate and key
- click on launch

I have to kill the script and relaunch and it start working normally.

**Comment by nickw444** [comment]
I too am having this issue @SimoneCarnio, were you able to resolve it?

**Comment by armandoagostini** [comment]
I too am having this issue @SimoneCarnio, were you able to resolve it?

**Comment by SimoneCarnio** [comment]
Sorry, I dismissed airnotifier and started to work to my own solution based on aws SNS as gateway, avoiding a lot of trouble with connections and timeouts

**Comment by zympolium** [comment]
Same problem here, i have to stop / launch APNs service for a success push but after X minutes : push notification fail again and if stop / launch again it works.
On process view all is fine :
Always a socket open on Apple :
tcp        0    362 10.1.3.4:59578          17.188.136.26:2195      ESTABLISHED 1381/python
When i stop / launch i see a new socket open :
tcp        0      0 10.1.3.4:50038          17.188.160.141:2195     ESTABLISHED 1381/python
Seems that Apple close the connection but AirNotifier doesn't see it (i don't known if it can be possible ?)
Hope it could help
