### ISSUE TITLE
uses mongo

### ISSUE THREAD

**Issue by AeroNotix** [airnotifier/airnotifier#96]

**Comment by dcai** [comment]
Hi @AeroNotix Could you please explain a bit more about "uses mongo"?

**Comment by AeroNotix** [comment]
It's a trollbaiting a little. But the fact that the project requires mongo, which is lauded as probably one of the worst "databases" in existence, may turn people off the project.

Is there a way to make airnotifier persistence backend agnostic?

**Comment by dcai** [comment]
Sorry, I'm not going to switch backend because you don't like MongoDB.

**Comment by AeroNotix** [comment]
It's not just I though, really. Your call ultimately. Enjoy!
