### ISSUE TITLE
How to add code for Android\iOS\Windows apps examples?

### ISSUE THREAD

**Issue by MakarkinPRO** [airnotifier/airnotifier#99]
Hello, do you or anybody have example of how to add code (or examples of the code) for apps? If you have android only it'll be awesome too!

Thx

**Comment by dcai** [comment]
Hi @MakarkinPRO I have one here: https://github.com/dcai/android-gcm-client-app

**Comment by dcai** [comment]
oops, I didn't push that repo, I will find it and push it :)

**Comment by dcai** [comment]
it's available now: https://github.com/dcai/android-gcm-client-app

**Comment by MakarkinPRO** [comment]
Amazing thx. Started to test, hope it'll run at my Android Studio as well )

**Comment by MakarkinPRO** [comment]
And is it actually simple to create a sample iOs app? Coz I started learning programming on Android just for 3rd day ... and didn't have MacBook or MacOS, but want to create apps for both platforms. Thx

**Comment by MakarkinPRO** [comment]
Spent several hours witout success. May you extraxt it to Android Studio like Exctract -> Android -> Gradle.

Or better create a github for Android Studio, I think there a lot of users (if they beginners) like me will be download what the Google says )

**Comment by dcai** [comment]
> And is it actually simple to create a sample iOs app? 
> Coz I started learning programming on Android just 
> for 3rd day ... and didn't have MacBook or MacOS, 
> but want to create apps for both platforms. Thx

Everyone is different, so I cannot comment which platform is easier to develop, since you have no apple device, it's better to go with android platform.
